version: '3.8'

services:
  web:
    image: ${REGISTRY:-localhost}/suyay_web:${TAG:-latest}
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      - DB_URL=mysql://root:suyay_password@db:3306/suyay_db
    volumes:
      - ./src:/var/www/html
    networks:
      - suyay-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
      # Removed the placement constraint to allow deployment on any node

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: suyay_password
      MYSQL_DATABASE: suyay_db
    ports:
      - "3309:3306"
    volumes:
      - ./suyayheroku1.sql:/docker-entrypoint-initdb.d/suyayheroku1.sql
      - mysql_data:/var/lib/mysql
    networks:
      - suyay-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

networks:
  suyay-network:
    driver: overlay

volumes:
  mysql_data:
    driver: local