version: '3.8'

services:
  web:
    image: ${REGISTRY:-ghcr.io}/${GITHUB_USERNAME:-pjcdz}/suyay_web:${TAG:-renew-coolify}
    depends_on:
      - db
    environment:
      - DB_URL=mysql://root:suyay_password@db:3306/suyay_db
    networks:
      - suyay-network
      - traefik_traefik-public
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.web.rule=Host(`app1.cardozo.com.ar`)"
        - "traefik.http.routers.web.entrypoints=web"
        - "traefik.http.services.web.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik_traefik-public"  # Match external network name exactly

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: suyay_password
      MYSQL_DATABASE: suyay_db
    ports:
      - "3309:3306"
    volumes:
      - ./suyayheroku1.sql:/docker-entrypoint-initdb.d/suyayheroku1.sql
      - mysql_data:/var/lib/mysql
    networks:
      - suyay-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

networks:
  suyay-network:
    driver: overlay
  traefik_traefik-public:
    external: true

volumes:
  mysql_data:
    driver: local
